/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiExplainSttRouteImport } from './routes/api/explain-stt'
import { Route as ApiExplainRouteImport } from './routes/api/explain'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAskStockRouteImport } from './routes/api/ask-stock'
import { Route as AuthenticatedSystemicRiskRouteImport } from './routes/_authenticated/systemic-risk'
import { Route as AuthenticatedSimulationRouteImport } from './routes/_authenticated/simulation'
import { Route as AuthenticatedMomentumRocketsRouteImport } from './routes/_authenticated/momentum-rockets'
import { Route as AuthenticatedFutureLeadersRouteImport } from './routes/_authenticated/future-leaders'
import { Route as AuthenticatedAnalogValidationRouteImport } from './routes/_authenticated/analog-validation'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedSystemicRiskValidationRouteImport } from './routes/_authenticated/systemic-risk.validation'
import { Route as AuthenticatedSystemicRiskV2RouteImport } from './routes/_authenticated/systemic-risk.v2'
import { Route as AuthenticatedSystemicRiskMethodologyRouteImport } from './routes/_authenticated/systemic-risk.methodology'
import { Route as AuthenticatedSystemicRiskEventsRouteImport } from './routes/_authenticated/systemic-risk.events'
import { Route as AuthenticatedSimulationValidationRouteImport } from './routes/_authenticated/simulation.validation'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicHooksSystemicRiskTickRouteImport } from './routes/api/public/hooks/systemic-risk-tick'
import { Route as ApiPublicHooksScanTickRouteImport } from './routes/api/public/hooks/scan-tick'
import { Route as ApiPublicHooksIngestFredRouteImport } from './routes/api/public/hooks/ingest-fred'
import { Route as ApiPublicHooksFutureLeadersTickRouteImport } from './routes/api/public/hooks/future-leaders-tick'
import { Route as ApiPublicHooksComputeRiskRouteImport } from './routes/api/public/hooks/compute-risk'
import { Route as ApiPublicHealthProvidersRouteImport } from './routes/api/public/health/providers'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiExplainSttRoute = ApiExplainSttRouteImport.update({
  id: '/api/explain-stt',
  path: '/api/explain-stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExplainRoute = ApiExplainRouteImport.update({
  id: '/api/explain',
  path: '/api/explain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskStockRoute = ApiAskStockRouteImport.update({
  id: '/api/ask-stock',
  path: '/api/ask-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSystemicRiskRoute =
  AuthenticatedSystemicRiskRouteImport.update({
    id: '/systemic-risk',
    path: '/systemic-risk',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSimulationRoute = AuthenticatedSimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMomentumRocketsRoute =
  AuthenticatedMomentumRocketsRouteImport.update({
    id: '/momentum-rockets',
    path: '/momentum-rockets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFutureLeadersRoute =
  AuthenticatedFutureLeadersRouteImport.update({
    id: '/future-leaders',
    path: '/future-leaders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalogValidationRoute =
  AuthenticatedAnalogValidationRouteImport.update({
    id: '/analog-validation',
    path: '/analog-validation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemicRiskValidationRoute =
  AuthenticatedSystemicRiskValidationRouteImport.update({
    id: '/validation',
    path: '/validation',
    getParentRoute: () => AuthenticatedSystemicRiskRoute,
  } as any)
const AuthenticatedSystemicRiskV2Route =
  AuthenticatedSystemicRiskV2RouteImport.update({
    id: '/v2',
    path: '/v2',
    getParentRoute: () => AuthenticatedSystemicRiskRoute,
  } as any)
const AuthenticatedSystemicRiskMethodologyRoute =
  AuthenticatedSystemicRiskMethodologyRouteImport.update({
    id: '/methodology',
    path: '/methodology',
    getParentRoute: () => AuthenticatedSystemicRiskRoute,
  } as any)
const AuthenticatedSystemicRiskEventsRoute =
  AuthenticatedSystemicRiskEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedSystemicRiskRoute,
  } as any)
const AuthenticatedSimulationValidationRoute =
  AuthenticatedSimulationValidationRouteImport.update({
    id: '/validation',
    path: '/validation',
    getParentRoute: () => AuthenticatedSimulationRoute,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSystemicRiskTickRoute =
  ApiPublicHooksSystemicRiskTickRouteImport.update({
    id: '/api/public/hooks/systemic-risk-tick',
    path: '/api/public/hooks/systemic-risk-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksScanTickRoute = ApiPublicHooksScanTickRouteImport.update({
  id: '/api/public/hooks/scan-tick',
  path: '/api/public/hooks/scan-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksIngestFredRoute =
  ApiPublicHooksIngestFredRouteImport.update({
    id: '/api/public/hooks/ingest-fred',
    path: '/api/public/hooks/ingest-fred',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksFutureLeadersTickRoute =
  ApiPublicHooksFutureLeadersTickRouteImport.update({
    id: '/api/public/hooks/future-leaders-tick',
    path: '/api/public/hooks/future-leaders-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksComputeRiskRoute =
  ApiPublicHooksComputeRiskRouteImport.update({
    id: '/api/public/hooks/compute-risk',
    path: '/api/public/hooks/compute-risk',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHealthProvidersRoute =
  ApiPublicHealthProvidersRouteImport.update({
    id: '/api/public/health/providers',
    path: '/api/public/health/providers',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/ai': typeof AuthenticatedAiRoute
  '/analog-validation': typeof AuthenticatedAnalogValidationRoute
  '/future-leaders': typeof AuthenticatedFutureLeadersRoute
  '/momentum-rockets': typeof AuthenticatedMomentumRocketsRoute
  '/simulation': typeof AuthenticatedSimulationRouteWithChildren
  '/systemic-risk': typeof AuthenticatedSystemicRiskRouteWithChildren
  '/api/ask-stock': typeof ApiAskStockRoute
  '/api/chat': typeof ApiChatRoute
  '/api/explain': typeof ApiExplainRoute
  '/api/explain-stt': typeof ApiExplainSttRoute
  '/simulation/validation': typeof AuthenticatedSimulationValidationRoute
  '/systemic-risk/events': typeof AuthenticatedSystemicRiskEventsRoute
  '/systemic-risk/methodology': typeof AuthenticatedSystemicRiskMethodologyRoute
  '/systemic-risk/v2': typeof AuthenticatedSystemicRiskV2Route
  '/systemic-risk/validation': typeof AuthenticatedSystemicRiskValidationRoute
  '/api/public/health/providers': typeof ApiPublicHealthProvidersRoute
  '/api/public/hooks/compute-risk': typeof ApiPublicHooksComputeRiskRoute
  '/api/public/hooks/future-leaders-tick': typeof ApiPublicHooksFutureLeadersTickRoute
  '/api/public/hooks/ingest-fred': typeof ApiPublicHooksIngestFredRoute
  '/api/public/hooks/scan-tick': typeof ApiPublicHooksScanTickRoute
  '/api/public/hooks/systemic-risk-tick': typeof ApiPublicHooksSystemicRiskTickRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/ai': typeof AuthenticatedAiRoute
  '/analog-validation': typeof AuthenticatedAnalogValidationRoute
  '/future-leaders': typeof AuthenticatedFutureLeadersRoute
  '/momentum-rockets': typeof AuthenticatedMomentumRocketsRoute
  '/simulation': typeof AuthenticatedSimulationRouteWithChildren
  '/systemic-risk': typeof AuthenticatedSystemicRiskRouteWithChildren
  '/api/ask-stock': typeof ApiAskStockRoute
  '/api/chat': typeof ApiChatRoute
  '/api/explain': typeof ApiExplainRoute
  '/api/explain-stt': typeof ApiExplainSttRoute
  '/': typeof AuthenticatedIndexRoute
  '/simulation/validation': typeof AuthenticatedSimulationValidationRoute
  '/systemic-risk/events': typeof AuthenticatedSystemicRiskEventsRoute
  '/systemic-risk/methodology': typeof AuthenticatedSystemicRiskMethodologyRoute
  '/systemic-risk/v2': typeof AuthenticatedSystemicRiskV2Route
  '/systemic-risk/validation': typeof AuthenticatedSystemicRiskValidationRoute
  '/api/public/health/providers': typeof ApiPublicHealthProvidersRoute
  '/api/public/hooks/compute-risk': typeof ApiPublicHooksComputeRiskRoute
  '/api/public/hooks/future-leaders-tick': typeof ApiPublicHooksFutureLeadersTickRoute
  '/api/public/hooks/ingest-fred': typeof ApiPublicHooksIngestFredRoute
  '/api/public/hooks/scan-tick': typeof ApiPublicHooksScanTickRoute
  '/api/public/hooks/systemic-risk-tick': typeof ApiPublicHooksSystemicRiskTickRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/analog-validation': typeof AuthenticatedAnalogValidationRoute
  '/_authenticated/future-leaders': typeof AuthenticatedFutureLeadersRoute
  '/_authenticated/momentum-rockets': typeof AuthenticatedMomentumRocketsRoute
  '/_authenticated/simulation': typeof AuthenticatedSimulationRouteWithChildren
  '/_authenticated/systemic-risk': typeof AuthenticatedSystemicRiskRouteWithChildren
  '/api/ask-stock': typeof ApiAskStockRoute
  '/api/chat': typeof ApiChatRoute
  '/api/explain': typeof ApiExplainRoute
  '/api/explain-stt': typeof ApiExplainSttRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/simulation/validation': typeof AuthenticatedSimulationValidationRoute
  '/_authenticated/systemic-risk/events': typeof AuthenticatedSystemicRiskEventsRoute
  '/_authenticated/systemic-risk/methodology': typeof AuthenticatedSystemicRiskMethodologyRoute
  '/_authenticated/systemic-risk/v2': typeof AuthenticatedSystemicRiskV2Route
  '/_authenticated/systemic-risk/validation': typeof AuthenticatedSystemicRiskValidationRoute
  '/api/public/health/providers': typeof ApiPublicHealthProvidersRoute
  '/api/public/hooks/compute-risk': typeof ApiPublicHooksComputeRiskRoute
  '/api/public/hooks/future-leaders-tick': typeof ApiPublicHooksFutureLeadersTickRoute
  '/api/public/hooks/ingest-fred': typeof ApiPublicHooksIngestFredRoute
  '/api/public/hooks/scan-tick': typeof ApiPublicHooksScanTickRoute
  '/api/public/hooks/systemic-risk-tick': typeof ApiPublicHooksSystemicRiskTickRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai'
    | '/analog-validation'
    | '/future-leaders'
    | '/momentum-rockets'
    | '/simulation'
    | '/systemic-risk'
    | '/api/ask-stock'
    | '/api/chat'
    | '/api/explain'
    | '/api/explain-stt'
    | '/simulation/validation'
    | '/systemic-risk/events'
    | '/systemic-risk/methodology'
    | '/systemic-risk/v2'
    | '/systemic-risk/validation'
    | '/api/public/health/providers'
    | '/api/public/hooks/compute-risk'
    | '/api/public/hooks/future-leaders-tick'
    | '/api/public/hooks/ingest-fred'
    | '/api/public/hooks/scan-tick'
    | '/api/public/hooks/systemic-risk-tick'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/ai'
    | '/analog-validation'
    | '/future-leaders'
    | '/momentum-rockets'
    | '/simulation'
    | '/systemic-risk'
    | '/api/ask-stock'
    | '/api/chat'
    | '/api/explain'
    | '/api/explain-stt'
    | '/'
    | '/simulation/validation'
    | '/systemic-risk/events'
    | '/systemic-risk/methodology'
    | '/systemic-risk/v2'
    | '/systemic-risk/validation'
    | '/api/public/health/providers'
    | '/api/public/hooks/compute-risk'
    | '/api/public/hooks/future-leaders-tick'
    | '/api/public/hooks/ingest-fred'
    | '/api/public/hooks/scan-tick'
    | '/api/public/hooks/systemic-risk-tick'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ai'
    | '/_authenticated/analog-validation'
    | '/_authenticated/future-leaders'
    | '/_authenticated/momentum-rockets'
    | '/_authenticated/simulation'
    | '/_authenticated/systemic-risk'
    | '/api/ask-stock'
    | '/api/chat'
    | '/api/explain'
    | '/api/explain-stt'
    | '/_authenticated/'
    | '/_authenticated/simulation/validation'
    | '/_authenticated/systemic-risk/events'
    | '/_authenticated/systemic-risk/methodology'
    | '/_authenticated/systemic-risk/v2'
    | '/_authenticated/systemic-risk/validation'
    | '/api/public/health/providers'
    | '/api/public/hooks/compute-risk'
    | '/api/public/hooks/future-leaders-tick'
    | '/api/public/hooks/ingest-fred'
    | '/api/public/hooks/scan-tick'
    | '/api/public/hooks/systemic-risk-tick'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAskStockRoute: typeof ApiAskStockRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiExplainRoute: typeof ApiExplainRoute
  ApiExplainSttRoute: typeof ApiExplainSttRoute
  ApiPublicHealthProvidersRoute: typeof ApiPublicHealthProvidersRoute
  ApiPublicHooksComputeRiskRoute: typeof ApiPublicHooksComputeRiskRoute
  ApiPublicHooksFutureLeadersTickRoute: typeof ApiPublicHooksFutureLeadersTickRoute
  ApiPublicHooksIngestFredRoute: typeof ApiPublicHooksIngestFredRoute
  ApiPublicHooksScanTickRoute: typeof ApiPublicHooksScanTickRoute
  ApiPublicHooksSystemicRiskTickRoute: typeof ApiPublicHooksSystemicRiskTickRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/explain-stt': {
      id: '/api/explain-stt'
      path: '/api/explain-stt'
      fullPath: '/api/explain-stt'
      preLoaderRoute: typeof ApiExplainSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/explain': {
      id: '/api/explain'
      path: '/api/explain'
      fullPath: '/api/explain'
      preLoaderRoute: typeof ApiExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask-stock': {
      id: '/api/ask-stock'
      path: '/api/ask-stock'
      fullPath: '/api/ask-stock'
      preLoaderRoute: typeof ApiAskStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/systemic-risk': {
      id: '/_authenticated/systemic-risk'
      path: '/systemic-risk'
      fullPath: '/systemic-risk'
      preLoaderRoute: typeof AuthenticatedSystemicRiskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulation': {
      id: '/_authenticated/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof AuthenticatedSimulationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/momentum-rockets': {
      id: '/_authenticated/momentum-rockets'
      path: '/momentum-rockets'
      fullPath: '/momentum-rockets'
      preLoaderRoute: typeof AuthenticatedMomentumRocketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/future-leaders': {
      id: '/_authenticated/future-leaders'
      path: '/future-leaders'
      fullPath: '/future-leaders'
      preLoaderRoute: typeof AuthenticatedFutureLeadersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analog-validation': {
      id: '/_authenticated/analog-validation'
      path: '/analog-validation'
      fullPath: '/analog-validation'
      preLoaderRoute: typeof AuthenticatedAnalogValidationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/systemic-risk/validation': {
      id: '/_authenticated/systemic-risk/validation'
      path: '/validation'
      fullPath: '/systemic-risk/validation'
      preLoaderRoute: typeof AuthenticatedSystemicRiskValidationRouteImport
      parentRoute: typeof AuthenticatedSystemicRiskRoute
    }
    '/_authenticated/systemic-risk/v2': {
      id: '/_authenticated/systemic-risk/v2'
      path: '/v2'
      fullPath: '/systemic-risk/v2'
      preLoaderRoute: typeof AuthenticatedSystemicRiskV2RouteImport
      parentRoute: typeof AuthenticatedSystemicRiskRoute
    }
    '/_authenticated/systemic-risk/methodology': {
      id: '/_authenticated/systemic-risk/methodology'
      path: '/methodology'
      fullPath: '/systemic-risk/methodology'
      preLoaderRoute: typeof AuthenticatedSystemicRiskMethodologyRouteImport
      parentRoute: typeof AuthenticatedSystemicRiskRoute
    }
    '/_authenticated/systemic-risk/events': {
      id: '/_authenticated/systemic-risk/events'
      path: '/events'
      fullPath: '/systemic-risk/events'
      preLoaderRoute: typeof AuthenticatedSystemicRiskEventsRouteImport
      parentRoute: typeof AuthenticatedSystemicRiskRoute
    }
    '/_authenticated/simulation/validation': {
      id: '/_authenticated/simulation/validation'
      path: '/validation'
      fullPath: '/simulation/validation'
      preLoaderRoute: typeof AuthenticatedSimulationValidationRouteImport
      parentRoute: typeof AuthenticatedSimulationRoute
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/systemic-risk-tick': {
      id: '/api/public/hooks/systemic-risk-tick'
      path: '/api/public/hooks/systemic-risk-tick'
      fullPath: '/api/public/hooks/systemic-risk-tick'
      preLoaderRoute: typeof ApiPublicHooksSystemicRiskTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scan-tick': {
      id: '/api/public/hooks/scan-tick'
      path: '/api/public/hooks/scan-tick'
      fullPath: '/api/public/hooks/scan-tick'
      preLoaderRoute: typeof ApiPublicHooksScanTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest-fred': {
      id: '/api/public/hooks/ingest-fred'
      path: '/api/public/hooks/ingest-fred'
      fullPath: '/api/public/hooks/ingest-fred'
      preLoaderRoute: typeof ApiPublicHooksIngestFredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/future-leaders-tick': {
      id: '/api/public/hooks/future-leaders-tick'
      path: '/api/public/hooks/future-leaders-tick'
      fullPath: '/api/public/hooks/future-leaders-tick'
      preLoaderRoute: typeof ApiPublicHooksFutureLeadersTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/compute-risk': {
      id: '/api/public/hooks/compute-risk'
      path: '/api/public/hooks/compute-risk'
      fullPath: '/api/public/hooks/compute-risk'
      preLoaderRoute: typeof ApiPublicHooksComputeRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health/providers': {
      id: '/api/public/health/providers'
      path: '/api/public/health/providers'
      fullPath: '/api/public/health/providers'
      preLoaderRoute: typeof ApiPublicHealthProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedSimulationRouteChildren {
  AuthenticatedSimulationValidationRoute: typeof AuthenticatedSimulationValidationRoute
}

const AuthenticatedSimulationRouteChildren: AuthenticatedSimulationRouteChildren =
  {
    AuthenticatedSimulationValidationRoute:
      AuthenticatedSimulationValidationRoute,
  }

const AuthenticatedSimulationRouteWithChildren =
  AuthenticatedSimulationRoute._addFileChildren(
    AuthenticatedSimulationRouteChildren,
  )

interface AuthenticatedSystemicRiskRouteChildren {
  AuthenticatedSystemicRiskEventsRoute: typeof AuthenticatedSystemicRiskEventsRoute
  AuthenticatedSystemicRiskMethodologyRoute: typeof AuthenticatedSystemicRiskMethodologyRoute
  AuthenticatedSystemicRiskV2Route: typeof AuthenticatedSystemicRiskV2Route
  AuthenticatedSystemicRiskValidationRoute: typeof AuthenticatedSystemicRiskValidationRoute
}

const AuthenticatedSystemicRiskRouteChildren: AuthenticatedSystemicRiskRouteChildren =
  {
    AuthenticatedSystemicRiskEventsRoute: AuthenticatedSystemicRiskEventsRoute,
    AuthenticatedSystemicRiskMethodologyRoute:
      AuthenticatedSystemicRiskMethodologyRoute,
    AuthenticatedSystemicRiskV2Route: AuthenticatedSystemicRiskV2Route,
    AuthenticatedSystemicRiskValidationRoute:
      AuthenticatedSystemicRiskValidationRoute,
  }

const AuthenticatedSystemicRiskRouteWithChildren =
  AuthenticatedSystemicRiskRoute._addFileChildren(
    AuthenticatedSystemicRiskRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedAnalogValidationRoute: typeof AuthenticatedAnalogValidationRoute
  AuthenticatedFutureLeadersRoute: typeof AuthenticatedFutureLeadersRoute
  AuthenticatedMomentumRocketsRoute: typeof AuthenticatedMomentumRocketsRoute
  AuthenticatedSimulationRoute: typeof AuthenticatedSimulationRouteWithChildren
  AuthenticatedSystemicRiskRoute: typeof AuthenticatedSystemicRiskRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedAnalogValidationRoute: AuthenticatedAnalogValidationRoute,
  AuthenticatedFutureLeadersRoute: AuthenticatedFutureLeadersRoute,
  AuthenticatedMomentumRocketsRoute: AuthenticatedMomentumRocketsRoute,
  AuthenticatedSimulationRoute: AuthenticatedSimulationRouteWithChildren,
  AuthenticatedSystemicRiskRoute: AuthenticatedSystemicRiskRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAskStockRoute: ApiAskStockRoute,
  ApiChatRoute: ApiChatRoute,
  ApiExplainRoute: ApiExplainRoute,
  ApiExplainSttRoute: ApiExplainSttRoute,
  ApiPublicHealthProvidersRoute: ApiPublicHealthProvidersRoute,
  ApiPublicHooksComputeRiskRoute: ApiPublicHooksComputeRiskRoute,
  ApiPublicHooksFutureLeadersTickRoute: ApiPublicHooksFutureLeadersTickRoute,
  ApiPublicHooksIngestFredRoute: ApiPublicHooksIngestFredRoute,
  ApiPublicHooksScanTickRoute: ApiPublicHooksScanTickRoute,
  ApiPublicHooksSystemicRiskTickRoute: ApiPublicHooksSystemicRiskTickRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
